In [ ]:
!pip3 install h2o --upgrade

Collecting h2o
  Downloading h2o-3.46.0.5.tar.gz (265.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 265.6/265.6 MB 4.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from h2o) (2.32.3)
Requirement already satisfied: tabulate in /usr/local/lib/python3.10/dist-packages (from h2o) (0.9.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->h2o) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->h2o) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->h2o) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->h2o) (2024.8.30)
Building wheels for collected packages: h2o
  Building wheel for h2o (setup.py) ... done
  Created wheel for h2o: filename=h2o-3.46.0.5-py2.py3-none-any.whl size=265646558 sha256=ce5d4cfa5b750352fbee6d224a22deed73006f65e5b93be99c9212cd882ac884
  Stored in directory: /root/.cache/pip/wheels/1a/46/4f/9b366522399306d7849672d58aefb44c9b73378d710bde2853
Successfully built h2o
Installing collected packages: h2o
Successfully installed h2o-3.46.0.5

In [ ]:
import h2o
from h2o.automl import H2OAutoML

In [ ]:
print(h2o.__version__)

3.46.0.5

In [ ]:
h2o.init()

Checking whether there is an H2O instance running at http://localhost:54321..... not found.
Attempting to start a local H2O server...
  Java Version: openjdk version "11.0.24" 2024-07-16; OpenJDK Runtime Environment (build 11.0.24+8-post-Ubuntu-1ubuntu322.04); OpenJDK 64-Bit Server VM (build 11.0.24+8-post-Ubuntu-1ubuntu322.04, mixed mode, sharing)
  Starting server from /usr/local/lib/python3.10/dist-packages/h2o/backend/bin/h2o.jar
  Ice root: /tmp/tmpz6ctplp7
  JVM stdout: /tmp/tmpz6ctplp7/h2o_unknownUser_started_from_python.out
  JVM stderr: /tmp/tmpz6ctplp7/h2o_unknownUser_started_from_python.err
  Server is running at http://127.0.0.1:54321
Connecting to H2O server at http://127.0.0.1:54321 ... successful.

--------------------------  -----------------------------------------------------------------------------------------
H2O_cluster_uptime:         02 secs
H2O_cluster_timezone:       Etc/UTC
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.46.0.5
H2O_cluster_version_age:    1 month
H2O_cluster_name:           H2O_from_python_unknownUser_fridsy
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    3.170 Gb
H2O_cluster_total_cores:    2
H2O_cluster_allowed_cores:  2
H2O_cluster_status:         locked, healthy
H2O_connection_url:         http://127.0.0.1:54321
H2O_connection_proxy:       {"http": null, "https": null, "colab_language_server": "/usr/colab/bin/language_service"}
H2O_internal_security:      False
Python_version:             3.10.12 final
--------------------------  -----------------------------------------------------------------------------------------

In [ ]:
import time
h2o.cluster().shutdown()
time.sleep(2)

H2O session _sid_a2e6 closed.

In [ ]:
import h2o
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# Load the transaction data
df1 = pd.read_csv('/content/drive/MyDrive/Fraud Dataset/transaction_dataset_corrected (1) (2).csv')
df1.head()

,Transaction ID,Timestamp,Sender Account,Transaction Type,IN_OUT,Amount,Recipient Bank,Fraud
0,T00001,5/20/2023 22:28,10035,Payment,Out,7580.39,B0005,0
1,T00002,6/16/2023 19:29,10072,Transfer,In,4946.84,B0008,0
2,T00003,6/13/2023 0:45,10015,Transfer,Out,2856.89,B0003,0
3,T00004,11/10/2023 23:10,10054,Transfer,Out,1047.93,B0007,0
4,T00005,12/14/2023 16:52,10062,Credit,Out,4333.85,B0005,0

In [ ]:
#load customer data
df2 = pd.read_csv('/content/drive/MyDrive/Fraud Dataset/customer_dataset 1.csv')
df2.head()

,Customer ID,Name,Age,Location,Gender,Account Type,Device Count
0,10001,Nimal Fernando,61,Jaffna,Female,Savings,5
1,10002,Sunil Samarasinghe,60,Jaffna,Other,Current,3
2,10003,Ruwan Jayasinghe,67,Galle,Other,Savings,1
3,10004,Lakshan Perera,19,Anuradhapura,Female,Savings,5
4,10005,Ruwan Kumara,52,Ratnapura,Other,Current,4

In [ ]:
# Merge the datasets
merged_data = pd.merge(df1, df2, left_on='Sender Account', right_on='Customer ID')

In [ ]:
merged_data.head(10)

,Transaction ID,Timestamp,Sender Account,Transaction Type,IN_OUT,Amount,Recipient Bank,Fraud,Customer ID,Name,Age,Location,Gender,Account Type,Device Count
0,T00001,5/20/2023 22:28,10035,Payment,Out,7580.39,B0005,0,10035,Chathura Wijesinghe,75,Matara,Male,Savings,1
1,T00027,10/26/2023 3:09,10035,Credit,Out,2944.02,B0009,0,10035,Chathura Wijesinghe,75,Matara,Male,Savings,1
2,T00028,2/10/2023 15:06,10035,Payment,Out,3336.11,B0006,0,10035,Chathura Wijesinghe,75,Matara,Male,Savings,1
3,T00069,12/3/2023 6:00,10035,Transfer,Out,5570.14,B0005,0,10035,Chathura Wijesinghe,75,Matara,Male,Savings,1
4,T00099,7/13/2023 12:45,10035,Credit,Out,7185.45,B0010,0,10035,Chathura Wijesinghe,75,Matara,Male,Savings,1
5,T00182,5/12/2023 2:41,10035,Transfer,In,162.31,B0003,1,10035,Chathura Wijesinghe,75,Matara,Male,Savings,1
6,T00212,9/5/2023 2:27,10035,Debit,In,2977.93,B0004,0,10035,Chathura Wijesinghe,75,Matara,Male,Savings,1
7,T00382,12/3/2023 2:10,10035,Payment,Out,3220.25,B0006,0,10035,Chathura Wijesinghe,75,Matara,Male,Savings,1
8,T00515,12/30/2023 11:14,10035,Payment,Out,6339.85,B0010,0,10035,Chathura Wijesinghe,75,Matara,Male,Savings,1
9,T00582,1/1/2023 23:53,10035,Debit,In,6856.40,B0007,0,10035,Chathura Wijesinghe,75,Matara,Male,Savings,1

In [ ]:
df = merged_data.drop(['Transaction ID','Name','Timestamp'], axis=1)

In [ ]:
df.head()

,Sender Account,Transaction Type,IN_OUT,Amount,Recipient Bank,Fraud,Customer ID,Age,Location,Gender,Account Type,Device Count
0,10035,Payment,Out,7580.39,B0005,0,10035,75,Matara,Male,Savings,1
1,10035,Credit,Out,2944.02,B0009,0,10035,75,Matara,Male,Savings,1
2,10035,Payment,Out,3336.11,B0006,0,10035,75,Matara,Male,Savings,1
3,10035,Transfer,Out,5570.14,B0005,0,10035,75,Matara,Male,Savings,1
4,10035,Credit,Out,7185.45,B0010,0,10035,75,Matara,Male,Savings,1

In [ ]:
df.isnull().sum()

Sender Account      0
Transaction Type    0
IN_OUT              0
Amount              0
Recipient Bank      0
Fraud               0
Customer ID         0
Age                 0
Location            0
Gender              0
Account Type        0
Device Count        0
dtype: int64

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split


# Split the dataset into training and testing sets
df_train, df_test = train_test_split(df, test_size=0.2)

# Save the training set as a CSV file
df_train.to_csv("training_set.csv", index=False)

# Save the testing set as a CSV file
df_test.to_csv("testing_set.csv", index=False)

In [ ]:
import h2o
from h2o.automl import H2OAutoML
h2o.init()

Checking whether there is an H2O instance running at http://localhost:54321. connected.

--------------------------  -----------------------------------------------------------------------------------------
H2O_cluster_uptime:         3 mins 45 secs
H2O_cluster_timezone:       Etc/UTC
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.46.0.5
H2O_cluster_version_age:    1 month
H2O_cluster_name:           H2O_from_python_unknownUser_z4hhsn
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    3.103 Gb
H2O_cluster_total_cores:    2
H2O_cluster_allowed_cores:  2
H2O_cluster_status:         locked, healthy
H2O_connection_url:         http://localhost:54321
H2O_connection_proxy:       {"http": null, "https": null, "colab_language_server": "/usr/colab/bin/language_service"}
H2O_internal_security:      False
Python_version:             3.10.12 final
--------------------------  -----------------------------------------------------------------------------------------

In [ ]:
# Convert pandas DataFrame to H2OFrame
h2o_frame = h2o.H2OFrame(df_train)

# Specify the target column and ensure it's categorical
y = 'Fraud'
h2o_frame[y] = h2o_frame[y].asfactor()

# Define feature columns by removing the target column
x = h2o_frame.columns
x.remove(y)

Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%

In [ ]:
h2o_automl = H2OAutoML(sort_metric='mse', max_runtime_secs=5*60, seed=666)
h2o_automl.train(x=x, y=y, training_frame=h2o_frame)

AutoML progress: |███████████████████████████████████████████████████████████████| (done) 100%

Model Details
=============
H2OXGBoostEstimator : XGBoost
Model Key: XGBoost_3_AutoML_2_20240929_183919


Model Summary:
    number_of_trees
--  -----------------
    15

ModelMetricsBinomial: xgboost
** Reported on train data. **

MSE: 0.039234582136064476
RMSE: 0.19807721256132538
LogLoss: 0.13479609646341942
Mean Per-Class Error: 0.27531280329302193
AUC: 0.9095270773650089
AUCPR: 0.32396476519138157
Gini: 0.8190541547300179

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.1758789388479385
       0      1     Error    Rate
-----  -----  ----  -------  ----------------
0      69594  5664  0.0753   (5664.0/75258.0)
1      1891   2087  0.4754   (1891.0/3978.0)
Total  71485  7751  0.0953   (7555.0/79236.0)

Maximum Metrics: Maximum metrics at their respective thresholds
metric                       threshold    value     idx
---------------------------  -----------  --------  -----
max f1                       0.175879     0.35587   221
max f2                       0.106163     0.507933  291
max f0point5                 0.274557     0.367219  143
max accuracy                 0.442452     0.950767  57
max precision                0.670655     1         0
max recall                   0.0248681    1         378
max specificity              0.670655     1         0
max absolute_mcc             0.100894     0.350766  300
max min_per_class_accuracy   0.107033     0.819507  289
max mean_per_class_accuracy  0.0882249    0.853109  318
max tns                      0.670655     75258     0
max fns                      0.670655     3977      0
max fps                      0.00499295   75258     399
max tps                      0.0248681    3978      378
max tnr                      0.670655     1         0
max fnr                      0.670655     0.999749  0
max fpr                      0.00499295   1         399
max tpr                      0.0248681    1         378

Gains/Lift Table: Avg response rate:  5.02 %, avg score:  5.43 %
group    cumulative_data_fraction    lower_threshold    lift      cumulative_lift    response_rate    score       cumulative_response_rate    cumulative_score    capture_rate    cumulative_capture_rate    gain      cumulative_gain    kolmogorov_smirnov
-------  --------------------------  -----------------  --------  -----------------  ---------------  ----------  --------------------------  ------------------  --------------  -------------------------  --------  -----------------  --------------------
1        0.0100586                   0.431752           10.5966   10.5966            0.531995         0.470054    0.531995                    0.470054            0.106586        0.106586                   959.657   959.657            0.10163
2        0.0200414                   0.343142           7.93217   9.2694             0.39823          0.395931    0.465365                    0.433132            0.0791855       0.185772                   693.217   826.94             0.174491
3        0.0300747                   0.27303            6.31381   8.28338            0.316981         0.299415    0.415862                    0.388522            0.0633484       0.24912                    531.381   728.338            0.230624
4        0.0400828                   0.21326            4.99848   7.46319            0.250946         0.242144    0.374685                    0.351974            0.0500251       0.299145                   399.848   646.319            0.272756
5        0.0502423                   0.196053           4.37961   6.83965            0.219876         0.201547    0.343381                    0.321556            0.0444947       0.34364                    337.961   583.965            0.308906
6        0.100169                    0.174693           3.74102   5.29522            0.187816         0.182355    0.265844                    0.252175            0.186777        0.530417                   274.102   429.522            0.45299
7        0.150008                    0.157223           3.1222    4.57326            0.156749         0.168701    0.229598                    0.224442            0.155606        0.686023                   212.22    357.326            0.564348
8        0.203657                    0.107044           2.41778   4.00543            0.121383         0.117201    0.201091                    0.196191            0.129713        0.815737                   141.778   300.543            0.644433
9        0.301189                    0.0351119          1.53358   3.205              0.0769928        0.0844406   0.160905                    0.160004            0.149573        0.965309                   53.3584   220.5              0.699225
10       0.405901                    0.00880256         0.331296  2.46365            0.0166325        0.0246272   0.123686                    0.12508             0.0346908       1                          -66.8704  146.365            0.625502
11       0.503433                    0.00671524         0         1.98636            0                0.00807195  0.0997242                   0.102412            0               1                          -100      98.6362            0.522815
12       0.619251                    0.00662649         0         1.61485            0                0.00662649  0.0810728                   0.084497            0               1                          -100      61.4853            0.400874
13       0.700389                    0.00602383         0         1.42778            0                0.00607327  0.0716808                   0.075412            0               1                          -100      42.7779            0.315448
14       0.871081                    0.00499564         0         1.148              0                0.00500289  0.0576346                   0.061615            0               1                          -100      14.7998            0.135733
15       1                           0.00497978         0         1                  0                0.00497978  0.0502045                   0.0543136           0               1                          -100      0                  0

ModelMetricsBinomial: xgboost
** Reported on cross-validation data. **

MSE: 0.03982029513050027
RMSE: 0.19955023209833725
LogLoss: 0.1387856870531244
Mean Per-Class Error: 0.21699450421470204
AUC: 0.9038941319220688
AUCPR: 0.2919959887750047
Gini: 0.8077882638441376

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.14484370946884156
       0      1      Error    Rate
-----  -----  -----  -------  -----------------
0      65791  9467   0.1258   (9467.0/75258.0)
1      1226   2752   0.3082   (1226.0/3978.0)
Total  67017  12219  0.135    (10693.0/79236.0)

Maximum Metrics: Maximum metrics at their respective thresholds
metric                       threshold    value     idx
---------------------------  -----------  --------  -----
max f1                       0.144844     0.339816  252
max f2                       0.11166      0.498348  287
max f0point5                 0.275522     0.357447  140
max accuracy                 0.545638     0.949897  16
max precision                0.688778     1         0
max recall                   0.0194366    1         382
max specificity              0.688778     1         0
max absolute_mcc             0.0725974    0.343847  328
max min_per_class_accuracy   0.11166      0.819005  287
max mean_per_class_accuracy  0.0543637    0.85206   335
max tns                      0.688778     75258     0
max fns                      0.688778     3977      0
max fps                      0.00023739   75258     399
max tps                      0.0194366    3978      382
max tnr                      0.688778     1         0
max fnr                      0.688778     0.999749  0
max fpr                      0.00023739   1         399
max tpr                      0.0194366    1         382

Gains/Lift Table: Avg response rate:  5.02 %, avg score:  5.78 %
group    cumulative_data_fraction    lower_threshold    lift       cumulative_lift    response_rate    score        cumulative_response_rate    cumulative_score    capture_rate    cumulative_capture_rate    gain      cumulative_gain    kolmogorov_smirnov
-------  --------------------------  -----------------  ---------  -----------------  ---------------  -----------  --------------------------  ------------------  --------------  -------------------------  --------  -----------------  --------------------
1        0.0100459                   0.433506           8.9083     8.9083             0.447236         0.47675      0.447236                    0.47675             0.0894922       0.0894922                  790.83    790.83             0.0836457
2        0.0200035                   0.352964           8.60865    8.75914            0.432193         0.399314     0.439748                    0.438203            0.0857215       0.175214                   760.865   775.914            0.163414
3        0.0300116                   0.285397           6.48044    7.99925            0.325347         0.311952     0.401598                    0.396102            0.0648567       0.24007                    548.044   699.925            0.221162
4        0.0400071                   0.220017           4.70299    7.17571            0.236111         0.251623     0.360252                    0.360005            0.0470085       0.287079                   370.299   617.571            0.260132
5        0.0500404                   0.198622           3.70811    6.48044            0.186164         0.207363     0.325347                    0.3294              0.0372046       0.324284                   270.811   548.044            0.288739
6        0.100144                    0.177044           3.41676    4.94763            0.171537         0.1838       0.248393                    0.256554            0.171192        0.495475                   241.676   394.763            0.416228
7        0.150336                    0.152026           3.58604    4.49304            0.180035         0.166708     0.225571                    0.226558            0.17999         0.675465                   258.604   349.304            0.552887
8        0.200048                    0.113548           2.30588    3.94953            0.115765         0.123052     0.198284                    0.200836            0.11463         0.790096                   130.588   294.953            0.621236
9        0.300949                    0.0414452          1.6742     3.18667            0.0840525        0.089416     0.159985                    0.16348             0.168929        0.959025                   67.4205   218.667            0.69286
10       0.402633                    0.0211             0.400497   2.48303            0.0201067        0.0301401    0.124659                    0.129805            0.040724        0.999749                   -59.9503  148.303            0.628678
11       0.524332                    0.0165104          0.0020656  1.90719            0.000103702      0.0170736    0.0957493                   0.10364             0.000251383     1                          -99.7934  90.7187            0.500811
12       0.627354                    0.0165103          0          1.594              0                0.0165103    0.0800257                   0.0893317           0               1                          -100      59.3997            0.392344
13       0.75159                     0.00906515         0          1.33051            0                0.00949255   0.0667976                   0.0761345           0               1                          -100      33.0512            0.26154
14       0.812118                    0.00452368         0          1.23135            0                0.00533294   0.0618191                   0.0708576           0               1                          -100      23.1348            0.197813
15       0.90002                     0.00028136         0          1.11109            0                0.00281851   0.0557815                   0.0642124           0               1                          -100      11.1086            0.105265
16       1                           0.00021016         0          1                  0                0.000234928  0.0502045                   0.057816            0               1                          -100      0                  0

Cross-Validation Metrics Summary:
                         mean        sd            cv_1_valid    cv_2_valid    cv_3_valid    cv_4_valid    cv_5_valid
-----------------------  ----------  ------------  ------------  ------------  ------------  ------------  ------------
accuracy                 0.8760155   0.02028305    0.9121656     0.86407524    0.8672304     0.8681138     0.8684925
aic                      nan         0.0           nan           nan           nan           nan           nan
auc                      0.9041846   0.0022111305  0.9010446     0.9060167     0.90645295    0.9043099     0.90309876
err                      0.1239845   0.02028305    0.087834425   0.13592479    0.13276961    0.13188615    0.13150755
err_count                1964.8      321.38638     1392.0        2154.0        2104.0        2090.0        2084.0
f0point5                 0.27023715  0.018057855   0.30058286    0.2671862     0.26626655    0.25200236    0.26514784
f1                       0.3423557   0.0071087526  0.34153265    0.34845734    0.34698945    0.33055735    0.34424165
f2                       0.4729969   0.04409707    0.39539978    0.5007825     0.49795118    0.48026806    0.49058297
lift_top_group           8.956431    0.67136574    8.246967      9.905521      8.503555      8.770667      9.355444
loglikelihood            nan         0.0           nan           nan           nan           nan           nan
---                      ---         ---           ---           ---           ---           ---           ---
mcc                      0.33787873  0.018714633   0.306198      0.35156515    0.35051352    0.336318      0.34479895
mean_per_class_accuracy  0.76642597  0.04299266    0.6897946     0.7896768     0.7886967     0.78253084    0.781431
mean_per_class_error     0.23357402  0.04299266    0.31020543    0.21032321    0.21130326    0.21746917    0.218569
mse                      0.03982028  0.0011874959  0.04106293    0.040065344   0.040070146   0.03784146    0.040061515
pr_auc                   0.29360935  0.014533075   0.28933403    0.3185329     0.28973538    0.28023806    0.29020634
precision                0.2375098   0.023512457   0.27833462    0.23123243    0.23051547    0.21753794    0.22992854
r2                       0.16478874  0.007877667   0.16017476    0.17872493    0.16108066    0.16071378    0.16324961
recall                   0.644519    0.11365928    0.44186047    0.7067485     0.7013802     0.688         0.6846058
rmse                     0.19953221  0.002995404   0.20263991    0.2001633     0.20017529    0.19452882    0.20015372
specificity              0.888333    0.027693233   0.9377287     0.8726051     0.8760133     0.87706167    0.87825626
[22 rows x 8 columns]


Scoring History:
    timestamp            duration    number_of_trees    training_rmse    training_logloss    training_auc    training_pr_auc    training_lift    training_classification_error
--  -------------------  ----------  -----------------  ---------------  ------------------  --------------  -----------------  ---------------  -------------------------------
    2024-09-29 18:43:55  6.676 sec   0                  0.5              0.693147            0.5             0.0502045          1                0.949796
    2024-09-29 18:43:55  6.831 sec   5                  0.218874         0.208203            0.907046        0.311356           9.67473          0.0914357
    2024-09-29 18:43:56  6.908 sec   10                 0.199235         0.146615            0.908687        0.320097           10.4097          0.0856681
    2024-09-29 18:43:56  7.036 sec   15                 0.198077         0.134796            0.909527        0.323965           10.5966          0.0953481

Variable Importances:
variable                   relative_importance    scaled_importance      percentage
-------------------------  ---------------------  ---------------------  ----------------------
Sender Account             5774.14404296875       1.0                    0.433503860670187
Transaction Type.Transfer  1614.7261962890625     0.27964771648801096    0.12122836472515466
Transaction Type.Credit    1457.2000732421875     0.252366422174147      0.109401818316015
Amount                     1317.9453125           0.22824946913211822    0.09894702606469392
Customer ID                1076.474853515625      0.1864302042874151     0.08081821330412609
Transaction Type.Debit     923.6951293945312      0.15997091906969774    0.06934801101167201
Transaction Type.Payment   853.2603149414062      0.14777260639703513    0.0640599953744107
Device Count               75.8624496459961       0.01313830224557262    0.0056955047461075175
Age                        46.00185775756836      0.007966870485952878   0.0034536691131199413
Location.Ratnapura         23.09938621520996      0.004000486659722038   0.0017342264115490843
---                        ---                    ---                    ---
Account Type.Current       6.74836540222168       0.0011687213467490912  0.0005066452158633913
Gender.Other               5.992762565612793      0.0010378616330000041  0.00044991702474696656
Location.Jaffna            5.094916343688965      0.0008823673787447527  0.0003825096652152834
Recipient Bank.B0006       4.940831184387207      0.0008556820106356233  0.0003709414551165707
Account Type.Savings       4.795523643493652      0.0008305168017644491  0.0003600322399163451
Recipient Bank.B0008       4.5997467041015625     0.000796611007600812   0.00034533394724731967
Location.Trincomalee       3.987471103668213      0.0006905735419821763  0.00029936629652595886
IN_OUT.Out                 3.691405773162842      0.0006392992183244743  0.00027713867926709235
Recipient Bank.B0004       2.85868501663208       0.0004950837726525264  0.00021462072680003132
Recipient Bank.B0009       2.033721923828125      0.0003522118445078651  0.00015268519436792711
[30 rows x 4 columns]


[tips]
Use `model.explain()` to inspect the model.
--
Use `h2o.display.toggle_user_tips()` to switch on/off this section.

In [ ]:
h2o_models = h2o.automl.get_leaderboard(h2o_automl, extra_columns = "ALL")
h2o_models

model_id                                                       mse       auc    logloss     aucpr    mean_per_class_error      rmse    training_time_ms    predict_time_per_row_ms  algo
-------------------------------------------------------  ---------  --------  ---------  --------  ----------------------  --------  ------------------  -------------------------  ---------------
XGBoost_3_AutoML_2_20240929_183919                       0.0398203  0.903894   0.138786  0.291996                0.216995  0.19955                  556                   0.004346  XGBoost
StackedEnsemble_BestOfFamily_3_AutoML_2_20240929_183919  0.0398273  0.903487   0.133859  0.293241                0.217229  0.199568                3967                   0.026835  StackedEnsemble
StackedEnsemble_BestOfFamily_2_AutoML_2_20240929_183919  0.040023   0.902511   0.134373  0.290124                0.302101  0.200058                4766                   0.013915  StackedEnsemble
StackedEnsemble_AllModels_1_AutoML_2_20240929_183919     0.0400485  0.902324   0.134428  0.289216                0.294117  0.200121                5205                   0.035933  StackedEnsemble
GBM_2_AutoML_2_20240929_183919                           0.0400522  0.903082   0.135815  0.288844                0.271345  0.200131                4141                   0.008609  GBM
StackedEnsemble_BestOfFamily_1_AutoML_2_20240929_183919  0.0403266  0.900339   0.13546   0.281596                0.282236  0.200815                4324                   0.017913  StackedEnsemble
GBM_3_AutoML_2_20240929_183919                           0.040384   0.901028   0.137376  0.279696                0.266741  0.200958                4530                   0.009024  GBM
GBM_1_AutoML_2_20240929_183919                           0.0407445  0.898294   0.137258  0.276281                0.324771  0.201853                9470                   0.016208  GBM
GBM_4_AutoML_2_20240929_183919                           0.0412357  0.895806   0.141011  0.262485                0.308118  0.203066                4601                   0.008376  GBM
XGBoost_1_AutoML_2_20240929_183919                       0.0414243  0.895685   0.139296  0.269458                0.284705  0.20353                 3821                   0.00478   XGBoost
[16 rows x 10 columns]

In [ ]:
from h2o.model.regression import h2o_mean_squared_error

h2o_frame_test = h2o.H2OFrame(df_test)

y_pred = h2o_automl.predict(h2o_frame_test)
# Extract the prediction column corresponding to the '1' class (assuming 'Fraud' is 1/0)
# or the relevant class label if it's a multi-class problem
y_pred = y_pred['p1']  # Replace 'p1' with the appropriate column name if needed

y_actual = h2o.H2OFrame(df_test[['Fraud']])

h2o_mean_squared_error(y_actual, y_pred)

Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%
xgboost prediction progress: |███████████████████████████████████████████████████| (done) 100%
Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%

0.03978895471259775

In [ ]:
y_pred = y_pred.as_data_frame()
y_actual = y_actual.as_data_frame()
result = pd.concat([y_pred, y_actual], axis=1)
result

/usr/local/lib/python3.10/dist-packages/h2o/frame.py:1981: H2ODependencyWarning: Converting H2O frame to pandas dataframe using single-thread.  For faster conversion using multi-thread, install polars and pyarrow and use it as pandas_df = h2o_df.as_data_frame(use_multi_thread=True)

  warnings.warn("Converting H2O frame to pandas dataframe using single-thread.  For faster conversion using"
/usr/local/lib/python3.10/dist-packages/h2o/frame.py:1981: H2ODependencyWarning: Converting H2O frame to pandas dataframe using single-thread.  For faster conversion using multi-thread, install polars and pyarrow and use it as pandas_df = h2o_df.as_data_frame(use_multi_thread=True)

  warnings.warn("Converting H2O frame to pandas dataframe using single-thread.  For faster conversion using"

             p1  Fraud
0      0.006626      0
1      0.038387      0
2      0.166467      0
3      0.004980      0
4      0.004996      0
...         ...    ...
19805  0.004980      0
19806  0.006626      0
19807  0.005017      0
19808  0.006024      0
19809  0.008803      0

[19810 rows x 2 columns]

In [ ]:
# import matplotlib.pyplot as plt
# fig = plt.figure(figsize=(24,16))
# ax = fig.add_subplot(211)
# ax.plot(x,  label='Actual')
# ax.plot(y,  color='green', label='Prediction')
# # ax.plot(x_trained, errors_trained, color='red', label='Error')
# ax.set_title('Site used in training: {}'.format(df_train))
# ax.set_xticklabels([])
# ax.set_xlabel('time')
# ax.set_ylabel('usage kwh')

# ay = fig.add_subplot(212)
# ay.plot(x_untrained, actuals_untrained, label='Actual', color='black')
# ay.plot(x_untrained, predictions_untrained, color='green', label='Prediction')
# # ay.plot(x_untrained, errors_untrained, color='red', label='Error')
# ay.set_title('Site untrained: {}'.format(untrained_site))
# ay.set_xticklabels([])
# ay.set_xlabel('time')
# ay.set_ylabel('usage kwh')
# ax.legend()
# plt.show()